# Generated by Django 4.1.5 on 2023-01-04 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "codigo",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=20)),
                ("apellido_paterno", models.CharField(max_length=20)),
                ("apellido_materno", models.CharField(max_length=20)),
                ("dni", models.CharField(max_length=8)),
                (
                    "fecha_nacimiento",
                    models.DateTimeField(verbose_name="Fecha de nacimiento"),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        verbose_name=datetime.datetime(2023, 1, 4, 11, 30, 23, 370015)
                    ),
                ),
                ("estado", models.CharField(max_length=10)),
            ],
        ),
    ]
